<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>SimpleTinyPDF</RootNamespace>
    <AssemblyName>SimpleTinyPDF</AssemblyName>

    <!-- NuGet package metadata -->
    <PackageId>SimpleTinyPDF</PackageId>
    <Version>0.71.0</Version>
    <Authors>Greg Salzman</Authors>
    <Description>A small-but-mighty, zero-dependency PDF generation library for .NET</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>pdf;barcode;dotnet;report;invoice;label;letter;cmyk;forms;acroform;signature;zero-dependency;qr code</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/gregsalzman/simpletinypdf</PackageProjectUrl>
    <RepositoryUrl>https://github.com/gregsalzman/simpletinypdf.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>SimpleTinyPDF.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
